### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by nyy23**
@Nitrak

### CODE REVIEW

**Comment by Nitrak** [comment]
Individual Assignments was removed from the addon, was this intentional? I know several users are using it to only hear abilities on specific members of their raid they assign themselves.

I noticed a significant frame-drop when abilities are playing (Up to 25%) compared to before (up to 12.5%), we should probably investigate that before launching this.

If the class-ordering in the "Abilities" tab is sorted alphabetically it will make it easier for people to navigate since the list is long now with all abilities in the same one.

- Death Knight
- Demon Hunter
- Druid
- Hunter
- Mage
- Monk
- Paladin
- Priest
- Rogue
- Shaman
- Warlock
- Warrior

Overall, really nice work and will make the addon more maintainable.

**Comment by nyy23** [comment]
> Individual Assignments was removed from the addon, was this intentional?

Intentional. 

>I noticed a significant frame-drop when abilities are playing (Up to 25%) compared to before (up to 12.5%), we should probably investigate that before launching this.

We discussed this already on Discord. This might be only the case, if config menu is open while playing sounds. Didn`t notice any frame drops while raiding / doing m+ - tested it for ~3 weeks now.

>If the class-ordering in the "Abilities" tab is sorted alphabetically it will make it easier for people to navigate since the list is long now with all abilities in the same one.

Used Blizzards own sorting order. See https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/Constants.lua#L38

**Comment by Nitrak** [comment]
> > If the class-ordering in the "Abilities" tab is sorted alphabetically it will make it easier for people to navigate since the list is long now with all abilities in the same one.
> 
> Used Blizzards own sorting order. See https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/Constants.lua#L38

I still feel alphabetical ordering would make more sense, I can't comprehend why Blizzard has sorted them in such a weird order.

**Comment by nyy23** [comment]
@Nitrak 
- Some major changes to the config panel.
- Implemented alphabetical (and localized) class sorting.

**Pull request merged**
