### PR TITLE
changed wrong spell id

### PR DESCRIPTION
**Pull request by RishiKumarRay**

### CODE REVIEW

**Comment by nyy23** [comment]
@RishiKumarRay can you do the same changes in a branch based of 2.1.0 branch?

**Comment by RishiKumarRay** [comment]
@nyy23 hi , I have changed the branch now it will merge to branch 2.0.1 , please review

**Comment by Nitrak** [comment]
> @nyy23 hi , I have changed the branch now it will merge to branch 2.0.1 , please review

Nyy meant to delete this PR and branch and make a new branch from the 2.1.0 branch instead of from the main branch :). There are a lot of changes to the spelllist.lua from 2.0.1 to 2.1.0.

**Comment by RishiKumarRay** [comment]
ok i will do it @nyy23 i will do the changes

**Comment by nyy23** [comment]
Closing this and waiting for your new PR 👍

**Pull request closed without merging**
