### PR TITLE
Update Constants.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
About the Chinese voice pack.
They still hope to generate a Chinese voice document for publication as soon as possible (even if it is an empty document), and they can add their own voice files to the Chinese voice package. Because there are now four Chinese voice packs in the Chinese region.

**Comment by Nitrak** [comment]
We (@nyy23) is working on making it possible to make your own sound-pack add-on that you can control and VRA will pick it up. So it is possible to create custom voice packs!

I am quite busy atm, but I am sure Nyy will give an update on the progress at some point! :)

**Comment by nyy23** [comment]
@nanjuekaien1 
Before we can switch to real voicepacks, we need some way to provide at least one voicepack for each lang which is always in sync with latest VRA version. This can only be archived by automating voicepack creation based on VRA spelllist and automating the update process for "our" voicepacks.
The pipeline for this is nearly ready. Once the pipeline is in place, we can enable this feature.

**Comment by nanjuekaien1** [comment]
@nyy23
Only externals on you I tested this function at the party, my teammates gave me Power Infusion, I did not receive a voice prompt

**Comment by nyy23** [comment]
@nanjuekaien1 
I tested this right now - working as expected. Make sure you have enabled PI for Dungeon area.
Nevertheless, comment section for a pull request is not the right place to discuss this...

**Comment by Nitrak** [comment]
@nanjuekaien1 you can now upload your own addon in the same style as https://www.curseforge.com/wow/addons/vocal-raid-assistant-ana-sound-pack to support Chinese voices!
Look at how the addon is set up and you should be able to get your own to work easily!

If you want the addon more easily found name it something like:
Vocal Raid Assistant - Sound Pack [zhCN]

I will close this PR.

**Pull request closed without merging**
